### PR TITLE
Update for flarum 0.1.0-beta.8

### PR DESCRIPTION
**Pull request by jtojnar**
Closes: #4

### CODE REVIEW

**Comment by AmauryCarrade** [comment]
Hi, I just saw this pull request—for some reasons, I missed the notification. Thanks for it! I'll test it soon and merge it if everything is correct.

**Comment by jtojnar** [comment]
Any progress?

**Comment by eikoninaru** [comment]
@AmauryCarrade plz merge it

**Comment by AmauryCarrade** [comment]
> @AmauryCarrade plz merge it

@eikoninaru okay.

Really sorry for the delay—I kinda struggle to maintain all my open source projects these times. I tested everything and it's great! I'll merge the PR and publish it to Packagist.

Thanks again!

**Pull request merged**
